#!/usr/bin/env python3
"""
05c_run_digis_on_windows.py

Section 5 / Figure 5b-c and Supplementary Figures 12-13:
Run digIS on breakpoint-centered windows and matched random-control windows.

This is a thin, reproducible wrapper around digIS. It replaces fixed-path shell scripts
such as run_digis_breakpoints.sh and run_digis_random_hw2000.sh.

Inputs are normally generated by 05b_breakpoint_homology_analysis.py:
  breakpoints_windows.fa
  random_windows.fa

Outputs:
  outdir/breakpoints/digis_output/
  outdir/random/digis_output/
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
from pathlib import Path


def run_digis(input_fasta: Path, outdir: Path, digis_script: Path, python_bin: str, overwrite: bool = False) -> None:
    if not input_fasta.exists():
        raise FileNotFoundError(f"Missing input FASTA: {input_fasta}")

    if outdir.exists() and overwrite:
        shutil.rmtree(outdir)
    outdir.mkdir(parents=True, exist_ok=True)

    cmd = [
        python_bin,
        str(digis_script),
        "-i", str(input_fasta),
        "-o", str(outdir),
    ]

    print("[cmd]", " ".join(cmd))
    subprocess.run(cmd, check=True)


def main() -> None:
    ap = argparse.ArgumentParser(description="Run digIS on real breakpoint and random-control windows.")
    ap.add_argument("--breakpoint-windows", required=True, help="breakpoints_windows.fa")
    ap.add_argument("--random-windows", default=None, help="random_windows.fa")
    ap.add_argument("--outdir", required=True)
    ap.add_argument("--digis-script", required=True, help="Path to digIS_search.py")
    ap.add_argument("--python-bin", default="python3")
    ap.add_argument("--overwrite", action="store_true")
    args = ap.parse_args()

    outdir = Path(args.outdir)
    run_digis(
        input_fasta=Path(args.breakpoint_windows),
        outdir=outdir / "breakpoints" / "digis_output",
        digis_script=Path(args.digis_script),
        python_bin=args.python_bin,
        overwrite=args.overwrite,
    )

    if args.random_windows:
        run_digis(
            input_fasta=Path(args.random_windows),
            outdir=outdir / "random" / "digis_output",
            digis_script=Path(args.digis_script),
            python_bin=args.python_bin,
            overwrite=args.overwrite,
        )

    print("[done] digIS runs complete.")


if __name__ == "__main__":
    main()
